In [1]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# Read in csv to pandas
df = pd.read_csv('data.csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [9]:
# What is the average price of a BMW

# Get unique values for makes
print(df.Make.unique())

# subset those which are BMWs and display
df_BMW = df[df.Make =='BMW']
display(df_BMW.head())

#Get average price of a BMW
BMW_avg = df_BMW.MSRP.mean()
print(BMW_avg)

['BMW' 'Audi' 'FIAT' 'Mercedes-Benz' 'Chrysler' 'Nissan' 'Volvo' 'Mazda'
 'Mitsubishi' 'Ferrari' 'Alfa Romeo' 'Toyota' 'McLaren' 'Maybach'
 'Pontiac' 'Porsche' 'Saab' 'GMC' 'Hyundai' 'Plymouth' 'Honda'
 'Oldsmobile' 'Suzuki' 'Ford' 'Cadillac' 'Kia' 'Bentley' 'Chevrolet'
 'Dodge' 'Lamborghini' 'Lincoln' 'Subaru' 'Volkswagen' 'Spyker' 'Buick'
 'Acura' 'Rolls-Royce' 'Maserati' 'Lexus' 'Aston Martin' 'Land Rover'
 'Lotus' 'Infiniti' 'Scion' 'Genesis' 'HUMMER' 'Tesla' 'Bugatti']


Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

61546.76347305389


In [17]:
# Number of missing values in "Engine HP" after 2015 (including 2015)

# Subset engine values after and including 2015
df_2015 = df[df.Year >= 2015]
display(df_2015)

# Get number of missing values in Engine HP column
HP_num_missing = df_2015['Engine HP'].isnull().sum()
print(HP_num_missing)

Make       Model  Year                Engine Fuel Type  Engine HP  \
32     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41      BMW    2 Series  2016     premium unleaded (required)      240.0   
42      BMW    2 Series  2016     premium unleaded (required)      240.0   
...     ...         ...   ...                             ...        ...   
11898   BMW          Z4  2015     premium unleaded (required)      300.0   
11899   BMW          Z4  2015     premium unleaded (required)      335.0   
11900   BMW          Z4  2016     premium unleaded (required)      300.0   
11901   BMW          Z4  2016     premium unleaded (required)      240.0   
11902   BMW          Z4  2016     premium unleaded (required)      335.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32                  4.0            MANUAL  rear wheel drive              2.0   
33                  4.0            MANUAL  rear wheel drive              2.0   
34                  4.0            MANUAL  rear wheel drive              2.0   
41                  4.0         AUTOMATIC  rear wheel drive              2.0   
42                  4.0         AUTOMATIC  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11898               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11899               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11900               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
32                 Performance      Compact   Convertible           35   
33                 Performance      Compact   Convertible           35   
34                 Performance      Compact   Convertible           35   
41          Luxury,Performance      Compact         Coupe           35   
42                      Luxury      Compact   Convertible           34   
...                        ...          ...           ...          ...   
11898  Luxury,High-Performance      Compact   Convertible           24   
11899  Luxury,High-Performance      Compact   Convertible           24   
11900  Luxury,High-Performance      Compact   Convertible           24   
11901       Luxury,Performance      Compact   Convertible           34   
11902  Luxury,High-Performance      Compact   Convertible           24   

       city mpg  Popularity   MSRP  
32           26         819  27495  
33           26         819  24995  
34           26         819  28195  
41           23        3916  32850  
42           23        3916  38650  
...         ...         ...    ...  
11898        17        3916  56950  
11899        17        3916  65800  
11900        17        3916  57500  
11901        22        3916  49700  
11902        17        3916  66350  

[5995 rows x 16 columns]

51


In [21]:
# Check if the mean of Engine HP change when na values missing

# Calculate the average "Engine HP" in the dataset.
avg_engine_hp = df['Engine HP'].mean()

# Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
df_fill = df['Engine HP'].fillna(value=avg_engine_hp)

# Now, calcualte the average of "Engine HP" again.
avg_engine_hp_fill = df_fill.mean()

# Has it changed?
print('Engine HP before fill: ' + str(round(avg_engine_hp)))
print('Engine HP after fill:  ' + str(round(avg_engine_hp_fill)))

Engine HP before fill: 249
Engine HP after fill:  249


In [34]:
# Sum of elements of the inverse matrix

# Select all the "Rolls-Royce" cars from the dataset.
df_rr = df[df['Make'] == "Rolls-Royce"]

# Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
df_rr_subset = df_rr[["Engine HP", "Engine Cylinders", "highway MPG"]]

# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
df_rr_subset = df_rr_subset.drop_duplicates()

# Get the underlying NumPy array. Let's call it X.
X = df_rr_subset.to_numpy()

# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = np.matmul(X.T, X)
print(XTX)

# Invert XTX.
inv_XTX = np.linalg.inv(XTX)

# What's the sum of all the elements of the result?
sum_inv_XTX = inv_XTX.sum()
print('Sum of XTX inverse: ' + str(sum_inv_XTX))

[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]
Sum of XTX inverse: 0.032212320677486125


In [35]:
# Normal equation

# Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300]
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w = np.matmul(np.matmul(inv_XTX, X.T), y)

# What's the value of the first element of w?.
w[0]

0.19989598183188972